/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ceyda
 */
public class KullaniciGiris extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGiris
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public KullaniciGiris() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        conn=db.connect_db();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_KullaniciAdi = new javax.swing.JTextField();
        txt_KullaniciSifre = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 190, 94));
        jLabel3.setText("HOTEL MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 60, 580, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 190, 94));
        jButton1.setText("GİRİŞ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(870, 580, 110, 40);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 190, 94));
        jLabel1.setText("KULLANICI ADI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 280, 190, 28);

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 193, 93));
        jLabel2.setText("ŞİFRE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 370, 80, 28);

        txt_KullaniciAdi.setBackground(new java.awt.Color(255, 255, 255));
        txt_KullaniciAdi.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_KullaniciAdi.setForeground(new java.awt.Color(242, 190, 94));
        txt_KullaniciAdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 190, 94)));
        jPanel1.add(txt_KullaniciAdi);
        txt_KullaniciAdi.setBounds(560, 280, 280, 40);

        txt_KullaniciSifre.setBackground(new java.awt.Color(255, 255, 255));
        txt_KullaniciSifre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_KullaniciSifre.setForeground(new java.awt.Color(242, 190, 94));
        txt_KullaniciSifre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 190, 94)));
        jPanel1.add(txt_KullaniciSifre);
        txt_KullaniciSifre.setBounds(560, 360, 280, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/26507_1100x700.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1060, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String sql="SELECT  KULLANICI_ADI, KULLANICI_SIFRE FROM KULLANICILAR WHERE (KULLANICI_ADI=? AND KULLANICI_SIFRE=?)";
       try {
            int count=0;
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_KullaniciAdi.getText());
            pst.setString(2, txt_KullaniciSifre.getText());
            rs=pst.executeQuery();
            while (rs.next()) {
                count++;
            }
            if (count==1) {
                KullaniciGiris A = new KullaniciGiris();
                AnaSayfa B = new AnaSayfa();
                this.setVisible(false);
                B.setVisible(true);
            }
            else {
                String kullanıcı=txt_KullaniciAdi.getText();
                String sifre=txt_KullaniciSifre.getText();
                if (kullanıcı.equals("") && sifre.equals("")) {
                    JOptionPane.showMessageDialog(null,"Kullanıcı Adı Veya Şifre Giriniz.");
                } else{
                JOptionPane.showMessageDialog(null,"Kullanıcı Adı Veya Şifre Hatalı.");   
                }
            }   
        }
        catch(Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
        finally {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_KullaniciAdi;
    private javax.swing.JPasswordField txt_KullaniciSifre;
    // End of variables declaration//GEN-END:variables
}
