/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ceyda
 */
public class MusteriEkle extends javax.swing.JFrame {

    /**
     * Creates new form MusteriEkle
     */
    
        Connection conn=null;
        PreparedStatement pst=null;
        Statement stmt = null;
        java.sql.ResultSet res=null;
        ResultSet rs=null;
        
    public MusteriEkle() {
        conn=db.connect_db();
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        veri_list();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_cocuksayisi = new javax.swing.JTextField();
        txt_yetiskinsayısı = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_telefonno = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tablo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb_odatipi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_isim = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_soyisim = new javax.swing.JTextField();
        txt_dogumtarihi = new javax.swing.JFormattedTextField();
        txt_kimlikno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_adres = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_cikistarihi = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(242, 190, 94));
        jLabel32.setText("YETİŞKİN SAYISI");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(80, 290, 200, 24);

        jLabel33.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(242, 190, 94));
        jLabel33.setText("ÇOCUK SAYISI");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(110, 340, 170, 24);

        txt_cocuksayisi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cocuksayisi.setForeground(new java.awt.Color(242, 190, 94));
        txt_cocuksayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cocuksayisiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cocuksayisi);
        txt_cocuksayisi.setBounds(290, 340, 180, 30);

        txt_yetiskinsayısı.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_yetiskinsayısı.setForeground(new java.awt.Color(242, 190, 94));
        txt_yetiskinsayısı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yetiskinsayısıActionPerformed(evt);
            }
        });
        jPanel1.add(txt_yetiskinsayısı);
        txt_yetiskinsayısı.setBounds(290, 290, 180, 30);

        jLabel28.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 190, 94));
        jLabel28.setText("KİMLİK/PASAPORT NO");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 70, 274, 30);

        jLabel29.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 190, 94));
        jLabel29.setText("DOĞUM TARİHİ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(90, 240, 200, 24);

        jLabel30.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 190, 94));
        jLabel30.setText("SOYİSİM");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(170, 160, 101, 24);

        txt_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(242, 190, 94));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(290, 400, 180, 30);

        txt_telefonno.setColumns(15);
        txt_telefonno.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_telefonno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0(###)-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefonno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_telefonno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonnoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_telefonno);
        txt_telefonno.setBounds(290, 200, 180, 30);

        tbl_tablo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OdaNO", "ODA TİPİ", "KAT", "BALKON"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_tablo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_tablo.setGridColor(new java.awt.Color(242, 190, 94));
        tbl_tablo.setName(""); // NOI18N
        tbl_tablo.setRowHeight(30);
        tbl_tablo.setSelectionBackground(new java.awt.Color(255, 214, 137));
        tbl_tablo.setSelectionForeground(new java.awt.Color(242, 190, 94));
        tbl_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tabloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_tablo);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(650, 70, 420, 560);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 190, 94));
        jLabel7.setText("YENİ MÜŞTERİ KAYIT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 10, 410, 41);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 190, 94));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        jButton1.setText("ANASAYFA");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 650, 200, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 190, 94));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N
        jButton2.setText("KAYDET");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(900, 650, 170, 40);

        cb_odatipi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cb_odatipi.setForeground(new java.awt.Color(242, 190, 94));
        cb_odatipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "TEK KİŞİLİK", "ÇİFT KİŞİLİK", "3 KİŞİLİK" }));
        cb_odatipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_odatipiActionPerformed(evt);
            }
        });
        jPanel1.add(cb_odatipi);
        cb_odatipi.setBounds(290, 590, 180, 30);

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 190, 94));
        jLabel6.setText("ADRES");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 450, 90, 24);

        txt_isim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_isim.setForeground(new java.awt.Color(242, 190, 94));
        txt_isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isimActionPerformed(evt);
            }
        });
        jPanel1.add(txt_isim);
        txt_isim.setBounds(290, 120, 180, 30);

        jLabel22.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 190, 94));
        jLabel22.setText("İSİM");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(210, 120, 60, 24);

        jLabel23.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 190, 94));
        jLabel23.setText("TELEFON NO");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(110, 200, 170, 24);

        jLabel26.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(242, 190, 94));
        jLabel26.setText("ODA TİPİ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(160, 590, 120, 24);

        txt_soyisim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_soyisim.setForeground(new java.awt.Color(242, 190, 94));
        txt_soyisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soyisimActionPerformed(evt);
            }
        });
        jPanel1.add(txt_soyisim);
        txt_soyisim.setBounds(290, 160, 180, 30);

        txt_dogumtarihi.setColumns(10);
        txt_dogumtarihi.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_dogumtarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_dogumtarihi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_dogumtarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dogumtarihiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dogumtarihi);
        txt_dogumtarihi.setBounds(290, 240, 180, 30);

        txt_kimlikno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_kimlikno.setForeground(new java.awt.Color(242, 190, 94));
        txt_kimlikno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kimliknoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kimlikno);
        txt_kimlikno.setBounds(290, 70, 180, 30);

        txt_adres.setColumns(20);
        txt_adres.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_adres.setForeground(new java.awt.Color(242, 190, 94));
        txt_adres.setRows(5);
        jScrollPane1.setViewportView(txt_adres);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 450, 180, 120);

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 190, 94));
        jLabel5.setText("E-MAİL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 400, 90, 24);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/26507_1100x700.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1130, 710);

        jLabel31.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 190, 94));
        jLabel31.setText("ÇIKIŞ TARİHİ");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(120, 320, 170, 24);

        txt_cikistarihi.setColumns(10);
        txt_cikistarihi.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_cikistarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cikistarihi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cikistarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cikistarihiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cikistarihi);
        txt_cikistarihi.setBounds(290, 320, 180, 30);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection baglan;
        
    private void txt_soyisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soyisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soyisimActionPerformed

    private void txt_kimliknoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kimliknoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kimliknoActionPerformed

    private void txt_telefonnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonnoActionPerformed

    }//GEN-LAST:event_txt_telefonnoActionPerformed

    private void txt_isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isimActionPerformed

    private void txt_dogumtarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dogumtarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dogumtarihiActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void cb_odatipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_odatipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_odatipiActionPerformed

    private void txt_cikistarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cikistarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cikistarihiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MusteriEkle C=new MusteriEkle();
        AnaSayfa B=new AnaSayfa();
        this.setVisible(false);
        B.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_yetiskinsayısıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yetiskinsayısıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yetiskinsayısıActionPerformed

    private void txt_cocuksayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cocuksayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cocuksayisiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         
      
        ekleme();
        //hesap();
        sifirla();
        veri_list();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tabloMouseClicked
   
        
        
    }//GEN-LAST:event_tbl_tabloMouseClicked
  public void sifirla(){
      
      txt_isim.setText("");
                 txt_soyisim.setText("");
                txt_dogumtarihi.setText("");
                 
                txt_telefonno.setText("");
               //txt_giristarihi.setText("");
                 txt_cikistarihi.setText("");
                 txt_email.setText("");
              txt_adres.setText("");
           cb_odatipi.setSelectedIndex(0);
      
      
      
      
  }
  /* public void hesap(){
            int a=Integer.parseInt(txt_giristarihi.getText());
            int b=50;

            int c = 50*a;
            String d = Integer.toString(c);


            JOptionPane.showMessageDialog(rootPane,"TOPLAM ÜCRET :"+d);


    }*/
    
    
    
    
    
    
    
    
    private void ekleme(){
        
        
            try {
            conn=db.connect_db();
          
                 
                 
                 String sql=" INSERT INTO MUSTERİLER(ISIM,SOYISIM,DOGUMTARIHI,TELEFONNO,GIRISTARIHI,CIKISTARIHI,EMAIL,ADRES,ODATIPI) "
                         + "VALUES(?,?,?,?,?,?,?,?,?)";
     
                 pst=conn.prepareStatement(sql);
                 pst.setString(1,txt_isim.getText());
                 pst.setString(2,txt_soyisim.getText());
                 pst.setString(3,txt_dogumtarihi.getText());
                 
                 pst.setString(4,txt_telefonno.getText());
                 //pst.setString(5,txt_giristarihi.getText());
                 pst.setString(6,txt_cikistarihi.getText());
                 pst.setString(7,txt_email.getText());
                 pst.setString(8,txt_adres.getText());
                 pst.setString(9,cb_odatipi.getSelectedItem().toString());
                 
                 
                 
                 pst.execute();

            JOptionPane.showMessageDialog(null,"Kayıt Oluşturuldu");
        }catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Kayıt Gerçekleştirilemedi.");
        }
            finally{
                try{
                    conn.close();
                }catch(Exception e){
                    
                }
            }
            
            
    }
     private void veri_list(){
           try{
             conn=db.connect_db();
             String sql="SELECT * FROM ODALAR ";
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             
                 while(rs.next()){
                     
            String data[]={rs.getString("ODANO"),rs.getString("ODATİPİ"),rs.getString("ODAKAT")
            ,rs.getString("ODABALKON"),
           };
             DefaultTableModel tblModel=(DefaultTableModel)tbl_tablo.getModel();
             tblModel.addRow(data);    
          
             
                 }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        finally{
            try{
                conn.close();
            }catch(Exception e){
                
                
                
            }
    }
     }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkle().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_odatipi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_tablo;
    private javax.swing.JTextArea txt_adres;
    private javax.swing.JFormattedTextField txt_cikistarihi;
    private javax.swing.JTextField txt_cocuksayisi;
    private javax.swing.JFormattedTextField txt_dogumtarihi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_isim;
    private javax.swing.JTextField txt_kimlikno;
    private javax.swing.JTextField txt_soyisim;
    private javax.swing.JFormattedTextField txt_telefonno;
    private javax.swing.JTextField txt_yetiskinsayısı;
    // End of variables declaration//GEN-END:variables
}
