/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ceyda
 */
public class Odalar extends javax.swing.JFrame {

    /**
     * Creates new form Odalar
     */
    
        Connection conn=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        
    public Odalar() {
        initComponents();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_OdaTipi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_Kat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_odadurum = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cb_Durum = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 190, 94));
        jLabel13.setText("DURUM");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(910, 80, 110, 28);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 190, 94));
        jLabel9.setText("ODA TİPİ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 80, 120, 28);

        cb_OdaTipi.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        cb_OdaTipi.setForeground(new java.awt.Color(242, 190, 94));
        cb_OdaTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "HEPSİ", "TEK KİŞİLİK", "ÇİFT KİŞİLİK", "3 KİŞİLİK" }));
        cb_OdaTipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_OdaTipiActionPerformed(evt);
            }
        });
        jPanel1.add(cb_OdaTipi);
        cb_OdaTipi.setBounds(500, 120, 170, 27);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 190, 94));
        jLabel10.setText("KAT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 80, 80, 28);

        cb_Kat.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        cb_Kat.setForeground(new java.awt.Color(242, 190, 94));
        cb_Kat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "HEPSİ", "1.KAT", "2.KAT", "3.KAT", "4.KAT", " " }));
        cb_Kat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_KatActionPerformed(evt);
            }
        });
        jPanel1.add(cb_Kat);
        cb_Kat.setBounds(40, 120, 140, 27);

        table_odadurum.setFont(new java.awt.Font("Garamond", 2, 18)); // NOI18N
        table_odadurum.setForeground(new java.awt.Color(242, 190, 94));
        table_odadurum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ODA NO", "İSİM", "SOYİSİM", "TELEFON NO", "GİRİŞ TARİHİ", "ÇIKIŞ TARİHİ", "KAT", "DURUM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_odadurum.setGridColor(new java.awt.Color(242, 190, 94));
        table_odadurum.setRowHeight(30);
        table_odadurum.setSelectionBackground(new java.awt.Color(205, 172, 111));
        jScrollPane1.setViewportView(table_odadurum);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 1080, 403);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 190, 94));
        jLabel1.setText("ODA DURUM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 10, 250, 41);

        cb_Durum.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        cb_Durum.setForeground(new java.awt.Color(242, 190, 94));
        cb_Durum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "DOLU", "TEMİZ", "KİRLİ", "ARIZALI", "REZERVE", "TADİLAT", " " }));
        cb_Durum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DurumActionPerformed(evt);
            }
        });
        jPanel1.add(cb_Durum);
        cb_Durum.setBounds(879, 120, 150, 27);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 190, 94));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        jButton1.setText("ANASAYFA");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 620, 200, 29);

        jButton5.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(242, 190, 94));
        jButton5.setText("GÖSTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(510, 610, 90, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/26507_1100x700.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1110, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_DurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DurumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_DurumActionPerformed

    private void cb_OdaTipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_OdaTipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_OdaTipiActionPerformed

    private void cb_KatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_KatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_KatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Odalar D=new Odalar();
        AnaSayfa B=new AnaSayfa();
        this.setVisible(false);
        B.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            conn=db.connect_db();
            Statement komut=conn.createStatement();
            ResultSet rs1=(ResultSet) komut.executeQuery("SELECT * FROM ODALAR" );
            ResultSetMetaData metaData = rs1.getMetaData();
            int kolunsayisi=metaData.getColumnCount();
            Vector vector_veriler=new Vector ();
            for(int t=0;t<kolunsayisi;t++){
                vector_veriler.addElement(metaData.getColumnLabel(t+1));
            }
            Vector vector_kayitlar=new Vector();
            while(rs1.next()){
                Vector vector_kayit=new Vector();
                for(int j=0;j<kolunsayisi;j++){
                    vector_kayit.addElement(rs1.getObject(j+1));

                }
                vector_kayitlar.addElement(vector_kayit);

            }

            DefaultTableModel dtm=new DefaultTableModel(vector_kayitlar,vector_veriler);
            table_odadurum.setModel(dtm);

        }
        catch(Exception ex){

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odalar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Durum;
    private javax.swing.JComboBox<String> cb_Kat;
    private javax.swing.JComboBox<String> cb_OdaTipi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_odadurum;
    // End of variables declaration//GEN-END:variables
}
